name: Run Notebook
on: workflow_dispatch

jobs:
        build:
                name: data_pipeline
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout code
                          uses: actions/checkout@v4

                        - name: install python
                          uses: actions/setup-python@v4
                          with:
                                  python-version: '3.10'
                        
                        - name: install dependency
                          run: pip install jupyter

                        - name: run the ipynb file
                          run: jupyter execute Employee_Turnover.ipynb